### ISSUE TITLE
Configuration file creation is not idempotent

### ISSUE THREAD

**Issue by peptoniet** [exterrestris/ansible-role-sanoid#15]
When I run the role against a computer that already has configured the /etc/sanoid/sanoid.conf file, the role overwrites this file with the default template.

I guess this task should be changed in main.yaml from:

```
- name: generate sanoid config
  ansible.builtin.template:
    src: ../templates/sanoid.conf.j2
    dest: "{{ sanoid_conf }}"
    owner: root
    group: root
    mode: '0600'
```

to:

```
- name: generate sanoid config
  ansible.builtin.template:
    src: ../templates/sanoid.conf.j2
    dest: "{{ sanoid_conf }}"
    owner: root
    group: root
    mode: '0600'
    force: false
```
